### ISSUE TITLE
Improve Model Loading Efficiency

### ISSUE THREAD

**Issue by saini-gk** [nikhiljangra264/VisionNova#1]
### Issue Title: Improve Model Loading Efficiency

**Description**:  
Currently, the model is loaded each time an image enhancement request is made. This can significantly slow down the application, especially with multiple simultaneous requests, as loading the model can be time-consuming.

**Impact**:  
- Users experience longer wait times for their image enhancements.
- Increased server load due to repeated model loading.
- Reduced overall responsiveness of the application.

**Suggested Solution**:
- Modify the application to load the model once during the initialization phase, and keep it in memory for subsequent requests.
- Ensure thread safety if the application runs in a multi-threaded environment.
- Consider implementing a way to reload the model if necessary (e.g., after updates).

**Acceptance Criteria**:  
- The model should only load once when the application starts.
- Application should maintain performance during high-load situations.
- Proper testing should be implemented to ensure functionality remains intact.

**Comment by nikhiljangra264** [comment]
Modify the Model class in model.py to has a function self.models
when a load_model function is called check if the function already exists in the self.models if yes then return it 
otherwise load using keras and then modify self.models and then return it
